// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvP-FpTbMz7ePv0_wO8QWgJzdA3sMOIvM',
    appId: '1:738671848360:web:aaae7c935b327b991dcb9d',
    messagingSenderId: '738671848360',
    projectId: 'influencers-app-dev',
    authDomain: 'influencers-app-dev.firebaseapp.com',
    storageBucket: 'influencers-app-dev.appspot.com',
    measurementId: 'G-2LNZWM3CV9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF-fhP-tEb38Q2CsVdUc7J0uOxxMo6EN4',
    appId: '1:738671848360:android:f2e8e5182844c4591dcb9d',
    messagingSenderId: '738671848360',
    projectId: 'influencers-app-dev',
    storageBucket: 'influencers-app-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWUpr6eIU5efvbyR-pkrdV46WaKC5zSYk',
    appId: '1:738671848360:ios:4f93caeb4fb97e2b1dcb9d',
    messagingSenderId: '738671848360',
    projectId: 'influencers-app-dev',
    storageBucket: 'influencers-app-dev.appspot.com',
    androidClientId: '738671848360-0h9mgtevrd6dq2ibik90phgn5h293f6i.apps.googleusercontent.com',
    iosClientId: '738671848360-lkmvmol6aa4k25phjq3tbmu35ndpph66.apps.googleusercontent.com',
    iosBundleId: 'com.example.testFirebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWUpr6eIU5efvbyR-pkrdV46WaKC5zSYk',
    appId: '1:738671848360:ios:4f93caeb4fb97e2b1dcb9d',
    messagingSenderId: '738671848360',
    projectId: 'influencers-app-dev',
    storageBucket: 'influencers-app-dev.appspot.com',
    androidClientId: '738671848360-0h9mgtevrd6dq2ibik90phgn5h293f6i.apps.googleusercontent.com',
    iosClientId: '738671848360-lkmvmol6aa4k25phjq3tbmu35ndpph66.apps.googleusercontent.com',
    iosBundleId: 'com.example.testFirebaseAuth',
  );
}
